<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('options')->delete();

        \DB::table('options')->insert(array (
            0 =>
            array (
                'id' => 1,
                'option_id' => NULL,
                'nombre' => 'Panel de Control',
                'ruta' => 'dashboard',
                'descripcion' => NULL,
                'icono_l' => 'text-primary fa-tachometer-alt',
                'icono_r' => NULL,
                'orden' => 0,
                'color' => 'bg-primary',
                'dev' => 0,
                'created_at' => '2020-03-06 14:09:05',
                'updated_at' => '2020-03-13 15:01:02',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'option_id' => NULL,
                'nombre' => 'Pedidos',
                'ruta' => 'pedidos.index',
                'descripcion' => NULL,
                'icono_l' => 'text-info fa-th',
                'icono_r' => NULL,
                'orden' => 2,
                'color' => 'bg-success',
                'dev' => 0,
                'created_at' => '2018-08-16 17:43:04',
                'updated_at' => '2020-03-07 08:48:53',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'option_id' => NULL,
                'nombre' => 'Nueva Venta',
                'ruta' => 'ventas.create',
                'descripcion' => 'Realizar nueva venta',
                'icono_l' => ' fas fa-solar-panel text-success',
                'icono_r' => NULL,
                'orden' => 1,
                'color' => 'bg-purple',
                'dev' => 0,
                'created_at' => '2017-04-15 22:38:52',
                'updated_at' => '2020-03-07 08:48:53',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'option_id' => NULL,
                'nombre' => 'Compras',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-shopping-cart',
                'icono_r' => 'fa-angle-left',
                'orden' => 3,
                'color' => 'bg-purple',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'option_id' => 4,
                'nombre' => 'Nueva Compra',
                'ruta' => 'compras.create',
                'descripcion' => NULL,
                'icono_l' => 'fa-cart-arrow-down',
                'icono_r' => NULL,
                'orden' => 4,
                'color' => 'bg-purple',
                'dev' => 0,
                'created_at' => '2017-04-13 22:39:13',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'option_id' => 4,
                'nombre' => 'Buscar Compras',
                'ruta' => 'compras.index',
                'descripcion' => 'Ingresos de artículos a inventario',
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'orden' => 5,
                'color' => 'bg-teal',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'option_id' => 4,
                'nombre' => 'Proveedores',
                'ruta' => 'proveedores.index',
                'descripcion' => 'Administración de proveedores',
                'icono_l' => 'fa-user-tie',
                'icono_r' => NULL,
                'orden' => 6,
                'color' => 'bg-warning',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'option_id' => 4,
                'nombre' => 'Estados',
                'ruta' => 'compraEstados.index',
                'descripcion' => 'Administración de estados de las compras',
                'icono_l' => 'fa-circle-notch',
                'icono_r' => '',
                'orden' => 14,
                'color' => 'bg-purple',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:19',
                'updated_at' => '2021-03-10 17:42:39',
                'deleted_at' => '2021-03-10 17:42:39',
            ),
            8 =>
            array (
                'id' => 9,
                'option_id' => 4,
                'nombre' => 'Tipos',
                'ruta' => 'compraTipos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-circle-notch',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => 'bg-success',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:19',
                'updated_at' => '2021-03-10 17:51:00',
                'deleted_at' => '2021-03-10 17:51:00',
            ),
            9 =>
            array (
                'id' => 10,
                'option_id' => NULL,
                'nombre' => 'Ventas',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-calculator',
                'icono_r' => 'fa-angle-left',
                'orden' => 7,
                'color' => 'bg-info',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:19',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'option_id' => 10,
                'nombre' => 'Buscar Venta',
                'ruta' => 'ventas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-search',
                'icono_r' => NULL,
                'orden' => 8,
                'color' => 'bg-primary',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:19',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'option_id' => 10,
                'nombre' => 'Estados',
                'ruta' => 'ventaEstados.index',
                'descripcion' => '',
                'icono_l' => 'fa-circle-notch',
                'icono_r' => '',
                'orden' => 7,
                'color' => 'bg-teal',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:19',
                'updated_at' => '2021-03-10 17:42:33',
                'deleted_at' => '2021-03-10 17:42:33',
            ),
            12 =>
            array (
                'id' => 13,
                'option_id' => 10,
                'nombre' => 'Clientes',
                'ruta' => 'clientes.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-address-book',
                'icono_r' => NULL,
                'orden' => 9,
                'color' => 'bg-danger',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:19',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'option_id' => 10,
                'nombre' => 'Tipos de pago',
                'ruta' => 'tipoPagos.index',
                'descripcion' => NULL,
                'icono_l' => 'far fa-circle',
                'icono_r' => NULL,
                'orden' => 10,
                'color' => 'bg-teal',
                'dev' => 0,
                'created_at' => '2018-11-22 23:02:27',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'option_id' => NULL,
                'nombre' => 'Artículos',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-barcode',
                'icono_r' => 'fa-angle-left',
                'orden' => 11,
                'color' => 'bg-info',
                'dev' => 0,
                'created_at' => '2019-07-01 22:29:53',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'option_id' => 15,
                'nombre' => 'Buscar Artículo',
                'ruta' => 'items.index',
                'descripcion' => 'Administración de los artículos',
                'icono_l' => 'fa-barcode',
                'icono_r' => NULL,
                'orden' => 12,
                'color' => 'bg-success',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'option_id' => 15,
                'nombre' => 'Nuevo Artículo',
                'ruta' => 'items.create',
                'descripcion' => NULL,
                'icono_l' => 'fa-plus',
                'icono_r' => NULL,
                'orden' => 13,
                'color' => NULL,
                'dev' => 0,
                'created_at' => '2020-03-22 14:53:43',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'option_id' => 15,
                'nombre' => 'Importar Excel',
                'ruta' => 'items.import.view',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-import',
                'icono_r' => NULL,
                'orden' => 14,
                'color' => NULL,
                'dev' => 0,
                'created_at' => '2020-10-15 15:25:15',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'option_id' => 15,
                'nombre' => 'Categorías',
                'ruta' => 'itemCategorias.index',
                'descripcion' => 'Administración de las categorías de los articulos',
                'icono_l' => 'fa-folder',
                'icono_r' => NULL,
                'orden' => 16,
                'color' => 'bg-orange',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-31 19:31:14',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'option_id' => 15,
                'nombre' => 'Unidades de medida',
                'ruta' => 'unimeds.index',
                'descripcion' => 'Administración de las unidades de medida',
                'icono_l' => 'fa-balance-scale',
                'icono_r' => NULL,
                'orden' => 17,
                'color' => 'bg-warning',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'option_id' => 15,
                'nombre' => 'Marcas',
                'ruta' => 'marcas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tags',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => 'bg-warning',
                'dev' => 0,
                'created_at' => '2017-05-19 23:20:31',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'option_id' => NULL,
                'nombre' => 'Admin',
                'ruta' => 'x',
                'descripcion' => 'Opciones de administración',
                'icono_l' => 'fa-folder',
                'icono_r' => 'fa-angle-left',
                'orden' => 18,
                'color' => 'bg-warning',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'option_id' => 22,
                'nombre' => 'Usuarios',
                'ruta' => 'users.index',
                'descripcion' => 'Administración de usuarios',
                'icono_l' => 'fa-users',
                'icono_r' => NULL,
                'orden' => 19,
                'color' => 'bg-orange',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'option_id' => 22,
                'nombre' => 'Roles',
                'ruta' => 'roles.index',
                'descripcion' => 'Administración de los roles de los usuarios',
                'icono_l' => 'fa-user-tag',
                'icono_r' => NULL,
                'orden' => 21,
                'color' => 'bg-orange',
                'dev' => 0,
                'created_at' => '2017-04-10 03:53:18',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'option_id' => 22,
                'nombre' => 'Permisos',
                'ruta' => 'permissions.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-key',
                'icono_r' => NULL,
                'orden' => 20,
                'color' => NULL,
                'dev' => 0,
                'created_at' => '2020-03-13 14:55:36',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'option_id' => 22,
                'nombre' => 'Configuraciones',
                'ruta' => 'profile.business',
                'descripcion' => NULL,
                'icono_l' => 'fa-cogs',
                'icono_r' => NULL,
                'orden' => 22,
                'color' => 'bg-teal',
                'dev' => 0,
                'created_at' => '2017-05-21 14:36:26',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'option_id' => NULL,
                'nombre' => 'Developer',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-code',
                'icono_r' => NULL,
                'orden' => 23,
                'color' => 'bg-teal',
                'dev' => 1,
                'created_at' => '2021-03-14 21:11:34',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'option_id' => 27,
                'nombre' => 'Prueba API\'S',
                'ruta' => 'dev.prueba.api',
                'descripcion' => NULL,
                'icono_l' => 'fa-check-circle',
                'icono_r' => NULL,
                'orden' => 26,
                'color' => 'bg-teal',
                'dev' => 1,
                'created_at' => '2020-08-26 11:46:42',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'option_id' => 27,
                'nombre' => 'Configuraciones',
                'ruta' => 'dev.configurations.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-cogs',
                'icono_r' => NULL,
                'orden' => 25,
                'color' => 'bg-teal',
                'dev' => 1,
                'created_at' => '2020-08-26 11:46:42',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'option_id' => 27,
                'nombre' => 'Menu',
                'ruta' => 'options.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-list',
                'icono_r' => NULL,
                'orden' => 24,
                'color' => 'bg-teal',
                'dev' => 1,
                'created_at' => '2020-08-26 11:46:42',
                'updated_at' => '2022-08-23 09:02:05',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'option_id' => NULL,
                'nombre' => 'E-Commerce',
                'ruta' => 'home',
                'descripcion' => NULL,
                'icono_l' => 'fab fa-internet-explorer',
                'icono_r' => NULL,
                'orden' => 27,
                'color' => 'bg-purple',
                'dev' => 0,
                'created_at' => '2020-03-06 14:01:04',
                'updated_at' => '2022-08-23 09:01:33',
                'deleted_at' => NULL,
            ),
        ));


    }
}
