<?php

return [
    "Papel para fotocopiadora",
    "Etiquetas multifunción",
    "Etiquetas adhesivas",
    "Cartulinas",
    "Papel continuo",
    "Papel reprografía planos",
    "Papel reprografía plotter",
    "Papel de oficina otros tipos",
    "Papel multiuso de colores",
    "Cartón pluma y cartón gris",
    "Recambios de anillas",
    "Papeles especiales para impresoras",
    "Etiqueta adhesiva de felicitación",
    "Bolígrafos",
    "Lápices",
    "Portaminas",
    "Rotuladores permanentes",
    "Rotuladores para pizarra",
    "Rotuladores para cd y dvd",
    "Rotuladores rollers",
    "Rotuladores con punta fina",
    "Rotuladores de fibra",
    "Rotuladores para ropa, marcadores para tela",
    "Rotuladores para cartelería",
    "Rotuladores y lápices fluorescentes",
    "Rotuladores otros modelos",
    "Minas para portaminas",
    "Plumas económicas",
    "Escritura estuchada belius",
    "Escritura estuchada parker",
    "Escritura estuchada waterman",
    "Escritura estuchada",
    "Escritura estuchada Caran d'Ache",
    "Recambios escritura",
    "Bolsas y fundas de archivo",
    "Archivadores de palanca",
    "Cajetines de archivo",
    "Cajas de archivo definitivo",
    "Bandejas de sobremesa",
    "Índices separadores",
    "Archivadores en módulos",
    "Separadores",
    "Carpetas colgantes y visores",
    "Subcarpetas de cartulina de colores",
    "Carpetas con fundas",
    "Carpetas de cartón con anillas",
    "Carpetas de anillas de polipropileno",
    "Carpetas de proyectos y listados",
    "Carpetas clasificadoras",
    "Carpetas con gomas de cartón",
    "Carpetas con gomas de polipropileno",
    "Carpetas miniclips",
    "Dossieres",
    "Ficheros de sobremesa",
    "Portafirmas y portamenús",
    "Álbumes y accesorios",
    "Revisteros",
    "Tijeras",
    "Guillotinas y Cizallas de papel",
    "Guillotinas automáticas y manuales",
    "Cutter",
    "Pegamentos en barra",
    "Correctores de cinta",
    "Correctores de frasco",
    "Correctores de lápiz",
    "Pegamentos universales",
    "Rollos adhesivos aironfix",
    "Adhesivos",
    "Sacapuntas",
    "Afilalápices eléctrico",
    "Pegamento en spray",
    "Abrecartas",
    "Colas escolares",
    "Planchas de corte",
    "Correctores en expositores",
    "Blocs para universitarios y oficina",
    "Bloc de notas Post-it",
    "Sobres",
    "Blocs y cuadernos escolares",
    "Blocs de dibujo",
    "Blocs de música",
    "Blocs de trabajos manuales",
    "Blocs de cartas",
    "Talonarios de entregas",
    "Talonarios de facturas",
    "Talonarios de pedidos y presupuestos",
    "Talonarios de camareros",
    "Talonarios de albarán",
    "Talonarios de recibos y vales",
    "Talonarios otros modelos",
    "Libros de contabilidad",
    "Papel para sumadoras y rollos de papel para calculadoras",
    "Papel térmico para fax",
    "Tacos de notas encolados",
    "Blocs de exámenes y milimetrados",
    "Tarjetas o postales",
    "Grapas",
    "Clips y chinchetas",
    "Quitagrapas",
    "Taladradores de sobremesa",
    "Taladradores de gran capacidad",
    "Taladradores repuestos",
    "Cubiletes",
    "Portaclips de plástico",
    "Portaclips imantado",
    "Porta clips de oficina",
    "Cintas métricas y metros",
    "Pesacartas",
    "Lupas",
    "Otros artículos de oficina",
    "Porta tarjetas plástico ",
    "Porta tarjetas de escritorio",
    "Numeradores",
    "Tampones de tinta",
    "Fechadores",
    "Mojasellos y dediles",
    "Sellos con fórmulas comerciales",
    "Sellos pre-entintados",
    "Imprentillas",
    "Tintas",
    "Caja de caudales",
    "Portamonedas",
    "Organizadores",
    "Apoyalibros",
    "Cajas para embalar",
    "Cintas adhesivas",
    "Portarollos para precintos",
    "Papel de embalar kraft",
    "Plástico de burbujas y film",
    "Portarollos y cierrabolsas",
    "Etiqueta de envío y sobre packing",
    "Portabobinas de papel",
    "Gomas elásticas y gomas de pollo",
    "Cintas y lazos de regalo",
    "Bolsas de plástico y papel",
    "Papel fantasía",
    "Otros accesorios de embalaje",
    "Agendas",
    "Recambios para agendas",
    "Escribanías y vades",
    "Listín de teléfonos y direcciones",
    "Carteras portadocumentos",
    "Carpetas portadocumentos",
    "Carpetas y carteras de piel",
    "Maletines y maletas",
    "Tarjeteros y recambios",
    "Calendarios y portacalendarios",
    "Calculadoras de sobremesa",
    "Calculadoras científicas",
    "Calculadoras impresoras",
    "Calculadoras de bolsillo",
    "Accesorios para calculadoras",
    "Grapadoras de bolsillo",
    "Grapadoras de sobremesa",
];
